name: 'airbnb'
version: '1.0.0'

# Set the profile to use for this project. Make sure 'default' is correctly configured in profiles.yml.
profile: 'default'

# Directories where dbt looks for different types of files
source-paths: ["models"]  # Path to your dbt models
analysis-paths: ["analysis"]  # Path to analysis files
test-paths: ["tests"]  # Path to test files
data-paths: ["data"]  # Path to seed data files
macro-paths: ["macros"]  # Path to macro files
snapshot-paths: ["snapshots"]  # Path to snapshot files

target-path: "target"  # Directory to store compiled SQL files
clean-targets:         # Directories to remove by `dbt clean`
  - "target"
  - "dbt_modules"

# Configuring models
models:
  airbnb:
    staging:
      schema: staging
      snowflake_Warehouse: COMPUTE_WH
      materialized: view  # Materialize staging models as views
    core:
      schema: core
      snowflake_Warehouse: COMPUTE_WH
      materialized: table  # Materialize core models as tables
